// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type UserAuthMethod struct {
	ID              pgtype.UUID
	UserProfileID   pgtype.UUID
	AuthProviderID  int64
	LoginIdentifier string
	SecretHash      pgtype.Text
	CreatedAt       pgtype.Timestamptz
}
